os: osx
osx_image: xcode11.6
notifications:
  email:
    recipients:
    - newfarry@126.com
    on_success: always
script:
- cat README.md
- brew update
- rm $(brew --repo homebrew/core)/gateway-go.rb
- cp gateway-go.rb $(brew --repo homebrew/core)
- brew test gateway-go
- brew audit --strict gateway-go
- brew style gateway-go
- cat $(brew --repo homebrew/core)/gateway-go.rb

deploy:
- provider: script
  skip_cleanup: true
  script: brew bump-formula-pr --tag=v0.1.91 --revision=8df96b8ae676344c14277c61ee8ac8bb206d8ef9
    --strict gateway-go
  on:
    tags: true
env:
  global:
    secure: UTbw1zSNvwoR+3d0E0NiOKmSETEjoqbQd4ARyPCfFamwHmOhMi2BM1MpFS/+2ZOs5vWD70iJRmPkWg2j6A9VkMVCF8oDT+NtPYo7DtdzmyZqc/Yb0kgOhKoY4Onj61JxWicIz2OapY7S6QqQGO2RJoQCh+2cI2n0wIhAl6ADHpcPZaKDtE85WOS5UkPqvucAz1KJkhGKIqHNk60tPArfQPVEOCSV3cLstxgkAwENsrPrVlc8NaNrBMlqlpQWOYYUEmUcTmdPWghNlXCZHZVWNT8FTUn8Yez6QpTsmEoWdgkbVe3msRntpIhyFhk6OB6cG1bjVaZi7NThpwt0WW6ZH+FchjqP2XTD/rr1jEDvSq5EgMSfcGvC1+/+hs9seAPERYFpXv3b/Z5H7B2m114OVxzr4nz3Pk7yQUZ3phKdrmnxCDMca2zdbmLOHhc8DZY/To/geDXDVQI3FFoibErUE5KdeMva9LMRmeaSTHtfgaXi61JlHz9BFcCH1TlpAav5j+uPQQmjsxMQ3o3OK2LpQmoWq6pO4c/sAEa4FgdxISNo/AGtGvtyUY6dRGTlDo2cVG4e6gA4MTMYlGHr10PVqf40K7oH7yhKqWV+x13ykVkdxaC8+1WKeVMfUIoVlI5EvMQOrrLhVwOLd/GvQjPsiD05WIMJMXZA+vD+XVFgpGU=
